encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki" # "wiki" is for the reference in html, wiki : <name in the path function>
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entryPage, name="entry"),
    path("search", views.search, name="search"),
    path("newPage", views.newPage, name="newPage"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("wiki/<str:title>/save", views.edit, name="save"),
    path("wiki/", views.randomPage, name="randomPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from dataclasses import fields
from random import choice
from turtle import title
from django.shortcuts import render
from django import forms
from . import util
from django.core.files.storage import default_storage
from django.urls import reverse
from django.http import HttpResponseRedirect
import markdown # For markdown language
# TODO on 11th May 2022: FIX SEARCH and EDIT functions, if available throw exceptions as well
class NewEntryForm(forms.Form):
    # label is like placeholder, remember to import forms from django
    title = forms.CharField(label="New encyclopedia title")
    entry = forms.CharField(label="New encyclopedia entry")

class SearchForm(forms.Form):
    title = forms.CharField(label="Search in this encyclopedia!")

class EditForm(forms.Form):
    title = forms.CharField(label="Enter existing encyclopedia title")
    entry = forms.CharField(label="Edit encyclopedia entry", widget=forms.Textarea)

def index(request):
    
    # if "entries" not in required.session:
    #    request.session["entries"] = []
    entries = util.list_entries()
    
    return render(request, "encyclopedia/index.html", {
        "entries": entries,
        "form": SearchForm()
    })

def entryPage(request, title):
    entry = util.get_entry(title)
    if entry is None:
        error_msg = "The entry does not exist!"
        return render(request, "encyclopedia/notfound.html", {
            "form": SearchForm(),
            "title": title,
            "error_msg": error_msg
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "form": SearchForm(),
            "entry": markdown.markdown(entry),
            "title": title
        })


def search(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            # for this function just make it simple, q for query
            entries = util.list_entries()
            data = form.cleaned_data.get("title")
            here = False
            for entry in entries:
                if data.lower() == entry.lower():
                    content_md = util.get_entry(data)
                    content_html = markdown.markdown(content_md)
                    here = True
                    break
                                   
                    """title = entry
                    content_md = markdown.markdown(util.get_entry(title)) """
            if here:
                return render(request, "encyclopedia/entry.html", {
                    "title": data,
                    "entry": content_html,
                    "form": form
                })
                    # return HttpResponseRedirect(reverse("entry", args=[title]))
            else:
                searches = [] # search_list is to show the results
                for entry in entries:
                    if data.lower() in entry.lower():
                        searches.append(entry)
            
            if len(searches) == 0:
                form = SearchForm()
                error_msg = data + "No matches"
                return render(request, "encyclopedia/notfound.html", {
                    "title": data,
                    "error_msg": error_msg} )
            
            else:
                return render(request,"encyclopedia/index.html", {
                    
                    "form": form,
                    "entries": searches   
                })
        
    else:
        search_msg = "Let's search!"
        return render(request, "encyclopedia/index.html", {
            "form": SearchForm(),
            "title": "",
            "error_msg": search_msg    
            })
        
    """if request.method == "GET":
        query = markdown.markdown(request.GET.get("q"))
        entries = util.list_entries()
        searches = []
        
        for entry in entries:
            if query.lower() in entry.lower():
                searches.append(entry)
        
        for entry in entries:
            if query.lower() == entry.lower():
                return render(request, "encyclopeda/entry.html", {
                    "title": entry
                })
            elif searches != []:
                return render(request, "encyclopedia.html", {
                    "searches": searches
                })
            else: 
                return render(request, "encyclopedia/notfound.html", {
                    "title": query
                })"""
                
            #if query_md.lower() == entry.lower():
            #    return render(request, "encyclopedia/entry.html", {
            #    "title": query,
            #    "entry": entry        
            #    }) 
                
"""elif search_list != []:
                return render(request, "encyclopedia/search.html", {
                    "entries": search_list
                }) 
                
            else:
                return render(request, "encyclopedia/notfound.html", {
                    "title": query
                })"""
        
            
def newPage(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["entry"]
            entries = util.list_entries()
            # title_md = markdown.markdown(title)
            
            for entry in entries:
                if entry.lower() == title.lower():
                    return render(request, "encyclopedia/newPage.html", {
                        "form": SearchForm(),
                        "newEntryForm": NewEntryForm(),
                        "error_message": "The entry is already existed!"
                    })
            
            new_entry = "# " + title
            new_content = "\n " + content        
            new_entry_content = new_entry + new_content
            util.save_entry(title, new_entry_content)
            entry_saved = util.get_entry(title)
            return render(request, "encyclopedia/entry.html", {
                "form": SearchForm(),
                "title" : title,
                "entry": markdown.markdown(entry_saved)

            })
        
    else:
        request.method == "GET"
        form = SearchForm()
        return render(request, "encyclopedia/newPage.html", {
            "form": form,
            "newEntryForm": NewEntryForm()
        })
    

def edit(request, title):
    if request.method == "POST":
        entry = util.get_entry(title)
        editForm = EditForm(initial={'title': title, 'entry': entry})
        return render(request, "encyclopedia/edit.html", {
            "form": SearchForm(),
            "editForm": editForm,
            "title": title,
            "entry": entry
        })


        #form = EditForm(request.POST)
        #if form.is_valid():
            #title_edited = form.cleaned_data.get("title")
            #entry_edited = form.cleaned_data.get("entry")
        ##   entry_edited = form.cleaned_data["entry"]
            
        #    util.save_entry(title_edited, entry_edited)
            
        #    entry = util.get_entry(entry_edited)
            
        #    return render(request, "encyclopedia/entry.html", {
        #        "form": SearchForm(),
        #        "title": title_edited,
        #        "entries": markdown.markdown(entry)
        #    })
    #else:
    #    request.method == "GET"
    #    return render(request, "encyclopedia/edit.html", {
    #        "form": SearchForm(),
    #        "editForm": EditForm({"title": title, "entry": util.get_entry(title)})
    #    })
        
            #lists = util.list_entries()
#title_md = markdown.markdown(title)
"""util.save_entry(title, entry)
            
            for list in lists:
                if title.lower() == list.lower():
                    return render
            return render(request, "encyclopedia/entry.html", {
                "title": title,
                "entry": entry
            })
        else:
            return render(request, "encyclopedia/entry.html", {
                "form": form,
                "editForm": EditForm()
            })"""
def save(request, title):
    if request.method == "POST":
        # Extract information from form
        form = EditForm(request.POST)
        if form.is_valid():
            entry_edited = form.cleaned_data["entry"]
            title_edited = form.cleaned_data["title"]
            if title_edited != title:
                filename = f"entries/{title}.md"
                if default_storage.exists(filename):
                    default_storage.delete(filename)
            util.save_entry(title_edited, entry_edited)
            entry = util.get_entry(title_edited)

        return render(request, "encyclopedia/entry.html", {
            "title": title_edited,
            "entry": markdown.markdown(entry),
            "form": SearchForm(),

        })            

def randomPage(request):
    title = choice(util.list_entries())
    return render(request, "encyclopedia/entry.html", {
        "title": title
        
    })
    #return HttpResponseRedirect(reverse("entryPage", args=[title]))
    #return entryPage(request, )
    # return HttpResponseRedirect(reverse("entry", args=[title]))

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Encyclopedia: {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit the existing content!</h1>
    <!-- <form action="{% url 'wiki:edit' title %}" method="POST"> -->
        <form action="{{ title }}/save" method = "POST">
        <strong>Content:</strong>
            {{ editForm }}
            {% csrf_token %}

            <button type="submit">Save</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit1.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Encyclopedia: {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit the existing content!</h1>
<div>
    <form action="{% url 'wiki:edit' title %}" method="POST">
        {% csrf_token %}
        <label for="title">Entry Title: </label>
        <input type="text" value="{{ title }}" name="title">
        <label for="entry">Enter your Entry: </label><br>
        <textarea name="entry" placeholder="{{ entry }}">{{ entry|safe }}</textarea>
        <input type="submit" value="Edit!">
    </form>
</div>

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Encyclopedia</h1>
    <a href="/wiki/{{ title }}/edit">Edit Your content!</a>
    <!-- <a href="/wiki/{{ title }}/edit">Edit Your content!</a> -->

    <!-- <a href="{% url 'wiki:edit' title %}">Edit Your content!</a> -->
    {{ entry|safe }}
    <form action="{{ title }}/edit" method = "POST">
        <!-- <input type="hidden" name="title" value="{{ title }}"> -->
        <button type="submit">Edit</button>
        {% csrf_token %}
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <!-- Not yet done, url entry has to be fixed-->
            <li><a href ="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}

    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="POST">
                    {% csrf_token %}
                    {{ form }} 
                <!--<input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newPage' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="/wiki/{{ title }}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Contribute to a new category in WIKI!</h1>
    {% if error %}
    {{error_message}}
    {% endif %}
    <form action="{% url 'wiki:newPage' %}" method="post">
        {% csrf_token %}
        {{ newEntryForm }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia NOT FOUND
{% endblock %}

{% block body %}

<i> {{title}} does not exist! </i>
<br><br>
{{ error_msg }}
<h3> Try to enter a valid input! </h3>

{% endblock %}